name = "mackley-payments"
main = "src/index.js"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "e23bc9f2899c5065f73cf561b5524378"
zone_id = "fab3fe670ea1c49cefb8cbfb30b2c657"

routes = [
  { pattern = "api.mackley.co/*", zone_id = "fab3fe670ea1c49cefb8cbfb30b2c657" }
]

durable_objects = { bindings = [
  { name = "SOCIAL_PROOF", class_name = "SocialProof" },
  { name = "ANALYTICS_STORE", class_name = "AnalyticsStore" },
  { name = "REFERRAL_STORE", class_name = "ReferralStore" },
  { name = "ORDER_STORE", class_name = "OrderStore" }
] }

migrations = [
  { tag = "v1", new_sqlite_classes = ["SocialProof"] },
  { tag = "v2", new_sqlite_classes = ["AnalyticsStore"] },
  { tag = "v3", new_sqlite_classes = ["ReferralStore"] },
  { tag = "v4", new_sqlite_classes = ["OrderStore"] }
]

[vars]
PAYMENTS_EMAIL_FROM = "MACKLEY <contact@mackley.co>"
